### ISSUE TITLE
Error while installing emlib

### ISSUE THREAD

**Issue by Nataliaktv** [gesellkammer/emlib#1]
I am on Pyrhon 3.7 Windows machine trying to install emlib. pip install emlib==0.4.0. (I tried other versions as well)
I am getting the following error: 
ERROR: Could not find a version that satisfies the requirement emlib==0.4.0 (from versions: none)
ERROR: No matching distribution found for emlib==0.4.0

**Comment by gesellkammer** [comment]
The last version is 0.9 and supports python >= 3.8. Please try that

**Comment by VandaDimit** [comment]
Hi, I am looking for a previous version of Emlib dating back to 2018, containing attributes Model, Calibration, TimeSeries and Observation, amongst others. Has this lib been based on previous versions of Emlib and would these still be accessible? Thanks

**Comment by gesellkammer** [comment]
I don't think that you are on the correct repo here.
